import { User } from "@/helpers/interfaces/user";

export const users: Array<User> = [
  {
    id: 1,
    avatar_url: "https://avatars.githubusercontent.com/u/1?v=4",
    url: "https://api.github.com/users/mojombo",
    login: "mojombo",
  },
  {
    id: 2,
    avatar_url: "https://avatars.githubusercontent.com/u/2?v=4",
    url: "https://api.github.com/users/defunkt",
    login: "defunkt",
  },
  {
    id: 3,
    avatar_url: "https://avatars.githubusercontent.com/u/3?v=4",
    url: "https://api.github.com/users/pjhyett",
    login: "pjhyett",
  },
  {
    id: 4,
    avatar_url: "https://avatars.githubusercontent.com/u/4?v=4",
    url: "https://api.github.com/users/wycats",
    login: "wycats",
  },
  {
    id: 5,
    avatar_url: "https://avatars.githubusercontent.com/u/5?v=4",
    url: "https://api.github.com/users/ezmobius",
    login: "ezmobius",
  },
  {
    id: 6,
    avatar_url: "https://avatars.githubusercontent.com/u/6?v=4",
    url: "https://api.github.com/users/ivey",
    login: "ivey",
  },
  {
    id: 7,
    avatar_url: "https://avatars.githubusercontent.com/u/7?v=4",
    url: "https://api.github.com/users/evanphx",
    login: "evanphx",
  },
  {
    id: 17,
    avatar_url: "https://avatars.githubusercontent.com/u/17?v=4",
    url: "https://api.github.com/users/vanpelt",
    login: "vanpelt",
  },
  {
    id: 18,
    avatar_url: "https://avatars.githubusercontent.com/u/18?v=4",
    url: "https://api.github.com/users/wayneeseguin",
    login: "wayneeseguin",
  },
  {
    id: 19,
    avatar_url: "https://avatars.githubusercontent.com/u/19?v=4",
    url: "https://api.github.com/users/brynary",
    login: "brynary",
  },
  {
    id: 20,
    avatar_url: "https://avatars.githubusercontent.com/u/20?v=4",
    url: "https://api.github.com/users/kevinclark",
    login: "kevinclark",
  },
  {
    id: 21,
    avatar_url: "https://avatars.githubusercontent.com/u/21?v=4",
    url: "https://api.github.com/users/technoweenie",
    login: "technoweenie",
  },
  {
    id: 22,
    avatar_url: "https://avatars.githubusercontent.com/u/22?v=4",
    url: "https://api.github.com/users/macournoyer",
    login: "macournoyer",
  },
  {
    id: 23,
    avatar_url: "https://avatars.githubusercontent.com/u/23?v=4",
    url: "https://api.github.com/users/takeo",
    login: "takeo",
  },
  {
    id: 25,
    avatar_url: "https://avatars.githubusercontent.com/u/25?v=4",
    url: "https://api.github.com/users/caged",
    login: "caged",
  },
  {
    id: 26,
    avatar_url: "https://avatars.githubusercontent.com/u/26?v=4",
    url: "https://api.github.com/users/topfunky",
    login: "topfunky",
  },
  {
    id: 27,
    avatar_url: "https://avatars.githubusercontent.com/u/27?v=4",
    url: "https://api.github.com/users/anotherjesse",
    login: "anotherjesse",
  },
  {
    id: 28,
    avatar_url: "https://avatars.githubusercontent.com/u/28?v=4",
    url: "https://api.github.com/users/roland",
    login: "roland",
  },
  {
    id: 29,
    avatar_url: "https://avatars.githubusercontent.com/u/29?v=4",
    url: "https://api.github.com/users/lukas",
    login: "lukas",
  },
  {
    id: 30,
    avatar_url: "https://avatars.githubusercontent.com/u/30?v=4",
    url: "https://api.github.com/users/fanvsfan",
    login: "fanvsfan",
  },
  {
    id: 31,
    avatar_url: "https://avatars.githubusercontent.com/u/31?v=4",
    url: "https://api.github.com/users/tomtt",
    login: "tomtt",
  },
  {
    id: 32,
    avatar_url: "https://avatars.githubusercontent.com/u/32?v=4",
    url: "https://api.github.com/users/railsjitsu",
    login: "railsjitsu",
  },
  {
    id: 34,
    avatar_url: "https://avatars.githubusercontent.com/u/34?v=4",
    url: "https://api.github.com/users/nitay",
    login: "nitay",
  },
  {
    id: 35,
    avatar_url: "https://avatars.githubusercontent.com/u/35?v=4",
    url: "https://api.github.com/users/kevwil",
    login: "kevwil",
  },
  {
    id: 36,
    avatar_url: "https://avatars.githubusercontent.com/u/36?v=4",
    url: "https://api.github.com/users/KirinDave",
    login: "KirinDave",
  },
  {
    id: 37,
    avatar_url: "https://avatars.githubusercontent.com/u/37?v=4",
    url: "https://api.github.com/users/jamesgolick",
    login: "jamesgolick",
  },
  {
    id: 38,
    avatar_url: "https://avatars.githubusercontent.com/u/38?v=4",
    url: "https://api.github.com/users/macournoyer",
    login: "macournoyer",
  },
];
