import { Montserrat } from "next/font/google";
import Head from "next/head";
import { PropsWithChildren } from "react";
import { useSelector } from "react-redux";
import { backgroundSelector } from "@/store";
import Background from "../background";
import Header from "../header";

const montserrat = Montserrat({
  subsets: ["latin"],
});
export default function Template({ children }: PropsWithChildren) {
  const background = useSelector(backgroundSelector);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={montserrat.className} style={{ height: "100%" }}>
        <Header />
        {children}
        <Background background={background.value} />
      </main>
    </>
  );
}
