import { Lora, Montserrat, Varela } from "next/font/google";
import Head from "next/head";
import { PropsWithChildren } from "react";
import { useSelector } from "react-redux";
import { backgroundData } from "@/datas/backgroundData";
import Background from "../background";
import Header from "../header";

const montserrat = Varela({
  subsets: ["latin"],
  weight: "400",
});
export default function Template({ children }: PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={montserrat.className}>
        <Header />
        {children}
        <Background background={backgroundData[0]} />
      </main>
    </>
  );
}
